#######################################################
# 
# MiniProject1_BankingSystem.py
# Python implementation of the Class Accounts
# Generated by Enterprise Architect
# Created on:      16-Sep-2021 8:16:37 PM
# Original author: caleb
# 
#######################################################


class Accounts:
    def ___account_type():
        pass

    def add_account():
        pass

    def balance():
        pass

    def del_account():
        pass

    def deposit():
        pass

    def withdrawl():
        pass