#######################################################
# 
# BankingSystem.py
# Python implementation of the Class BankingSystem
# Generated by Enterprise Architect
# Created on:      16-Sep-2021 8:16:52 PM
# Original author: caleb
# 
#######################################################
import Employee
import Customer

class BankingSystem:
    m_Employee= Employee()

    m_Customer= Customer()

    def __init__():
        pass

    def _confirm_emp():
        pass

    def _connect_emp_db():
        pass

    def _get_activity_dt():
        pass

    def _log_activity():
        pass

    def get_emp_info():
        pass

    def login():
        pass

    def logout():
        pass