#######################################################
# 
# Employee.py
# Python implementation of the Class Employee
# Generated by Enterprise Architect
# Created on:      16-Sep-2021 8:16:56 PM
# Original author: caleb
# 
#######################################################


class Employee:
    def add_employee():
        pass

    def del_employee():
        pass