#######################################################
# 
# Customer.py
# Python implementation of the Class Customer
# Generated by Enterprise Architect
# Created on:      16-Sep-2021 8:16:55 PM
# Original author: caleb
# 
#######################################################
import Accounts
import Services

class Customer:
    m_Accounts= Accounts()

    m_Services= Services()

    def _connect_cust_db():
        pass

    def add_customer():
        pass

    def del_customer():
        pass

    def get_customer_info():
        pass