#######################################################
# 
# Services.py
# Python implementation of the Class Services
# Generated by Enterprise Architect
# Created on:      16-Sep-2021 8:16:58 PM
# Original author: caleb
# 
#######################################################


class Services:
    def ___service_type():
        pass

    def add_service():
        pass

    def del_service():
        pass