#######################################################
# 
# Accounts.py
# Python implementation of the Class Accounts
# Generated by Enterprise Architect
# Created on:      20-Sep-2021 9:53:29 PM
# Original author: caleb
# 
#######################################################


class Accounts:
    def ___account_type():
        pass

    def add_account():
        pass

    def balance():
        pass

    def del_account():
        pass

    def deposit():
        pass

    def withdrawl():
        pass