#######################################################
# 
# BankingSystem.py
# Python implementation of the Class BankingSystem
# Generated by Enterprise Architect
# Created on:      20-Sep-2021 9:53:29 PM
# Original author: caleb
# 
#######################################################


class BankingSystem:
    def __init__():
        pass

    def _confirm_emp():
        pass

    def _connect_emp_db():
        pass

    def _get_activity_dt():
        pass

    def _log_activity():
        pass

    def get_emp_info():
        pass

    def login():
        pass

    def logout():
        pass