#######################################################
# 
# Employee.py
# Python implementation of the Class Employee
# Generated by Enterprise Architect
# Created on:      20-Sep-2021 9:53:30 PM
# Original author: caleb
# 
#######################################################


class Employee:
    def add_employee():
        pass

    def del_employee():
        pass