#######################################################
# 
# Customer.py
# Python implementation of the Class Customer
# Generated by Enterprise Architect
# Created on:      20-Sep-2021 11:10:39 PM
# Original author: caleb
# 
#######################################################


class Customer:
    def __init__():
        pass

    def _connect_cust_db():
        pass

    def add_customer():
        pass

    def del_customer():
        pass

    def get_customer_info():
        pass