#######################################################
# 
# Employee.py
# Python implementation of the Class Employee
# Generated by Enterprise Architect
# Created on:      20-Sep-2021 11:10:39 PM
# Original author: caleb
# 
#######################################################


class Employee:
    def __init__():
        pass

    def add_employee():
        pass

    def del_employee():
        pass