#######################################################
# 
# Employee.py
# Python implementation of the Class Employee
# Generated by Enterprise Architect
# Created on:      20-Sep-2021 11:10:39 PM
# Original author: caleb
# 
#######################################################
import BankingSystem


class Employee(BankingSystem.BankingSystem):

    def add_employee(self):
        pass

    def del_employee(self):
        pass
