#######################################################
# 
# Services.py
# Python implementation of the Class Services
# Generated by Enterprise Architect
# Created on:      20-Sep-2021 11:10:39 PM
# Original author: caleb
# 
#######################################################


class Services:
    def __init__():
        pass

    def _service_type():
        pass

    def add_service():
        pass

    def del_service():
        pass